name: Combine PRs

on:
  schedule:
    - cron: "0 1 * * 3" # Wednesday at 01:00
  workflow_dispatch:

jobs:
  combine-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Use GitHub App Token
        uses: wow-actions/use-app-token@d7957e08172ca2e8e49b35b8d266ad585885edc7 # pin@v2.0.2
        id: generate_token
        with:
          app_id: ${{ vars.COMBINE_PRS_APP_ID }} # The ID of the GitHub App
          private_key: ${{ secrets.COMBINE_PRS_PRIVATE_KEY }} # The private key of the GitHub App

      - name: combine-prs
        uses: github/combine-prs@v3.1.2
        with:
          github_token: ${{ steps.generate_token.outputs.BOT_TOKEN }}
          labels: combined-prs
          min_combine_number: 3
          title: "Combined dependabot PRs"
